import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("annotations", "0001_initial"),
        ("corpuses", "0001_initial"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalWorkspace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("workspace_type", models.CharField(choices=[("matter", "法务事项"), ("authority", "法律法规库"), ("playbook", "审查规则库"), ("template", "模板与范本库")], db_index=True, default="matter", max_length=32)),
                ("matter_type", models.CharField(choices=[("contract", "合同"), ("employment", "劳动人事"), ("compliance", "合规"), ("dispute", "争议"), ("general", "综合事项")], db_index=True, default="general", max_length=32)),
                ("matter_status", models.CharField(choices=[("active", "进行中"), ("waiting", "待补充"), ("completed", "已完成"), ("archived", "已归档")], db_index=True, default="active", max_length=32)),
                ("jurisdiction", models.CharField(db_index=True, default="CN-MAINLAND", max_length=64)),
                ("counterparty", models.CharField(blank=True, default="", max_length=512)),
                ("business_department", models.CharField(blank=True, default="", max_length=255)),
                ("confidentiality", models.CharField(choices=[("normal", "普通"), ("confidential", "机密"), ("highly_confidential", "高度机密")], default="confidential", max_length=32)),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("corpus", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="legal_workspace", to="corpuses.corpus")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="legal_workspaces", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-updated_at",)},
        ),
        migrations.CreateModel(
            name="ReviewProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("contract_type", models.CharField(db_index=True, max_length=128)),
                ("party_position", models.CharField(choices=[("buyer", "采购方"), ("seller", "供应方"), ("employer", "用人单位"), ("employee", "劳动者"), ("discloser", "披露方"), ("recipient", "接收方"), ("neutral", "中立审查")], db_index=True, default="neutral", max_length=32)),
                ("jurisdiction", models.CharField(db_index=True, default="CN-MAINLAND", max_length=64)),
                ("description", models.TextField(blank=True, default="")),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="legal_review_profiles", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("name", "-version")},
        ),
        migrations.CreateModel(
            name="PlaybookRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.CharField(db_index=True, max_length=64)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("severity", models.CharField(choices=[("critical", "严重"), ("high", "高"), ("medium", "中"), ("low", "低"), ("info", "提示")], db_index=True, default="medium", max_length=16)),
                ("required_terms", models.JSONField(blank=True, default=list)),
                ("prohibited_terms", models.JSONField(blank=True, default=list)),
                ("standard_position", models.TextField(blank=True, default="")),
                ("fallback_position", models.TextField(blank=True, default="")),
                ("suggested_language", models.TextField(blank=True, default="")),
                ("legal_basis_description", models.TextField(blank=True, default="")),
                ("sort_order", models.IntegerField(default=0)),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("review_profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rules", to="legal_workspace.reviewprofile")),
            ],
            options={"ordering": ("sort_order", "id")},
        ),
        migrations.CreateModel(
            name="ReviewRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("pending", "等待执行"), ("waiting_for_document", "等待文档"), ("parsing", "解析文档"), ("extracting", "提取合同事实"), ("matching_rules", "匹配审查规则"), ("analyzing", "分析风险"), ("verifying", "核验证据"), ("ready_for_review", "等待人工复核"), ("completed", "已完成"), ("failed", "失败"), ("cancelled", "已取消")], db_index=True, default="pending", max_length=32)),
                ("current_stage", models.CharField(blank=True, default="", max_length=64)),
                ("input_context", models.JSONField(blank=True, default=dict)),
                ("extracted_contract_data", models.JSONField(blank=True, default=dict)),
                ("summary", models.TextField(blank=True, default="")),
                ("model_name", models.CharField(blank=True, default="", max_length=128)),
                ("prompt_version", models.CharField(blank=True, default="", max_length=64)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_legal_review_runs", to=settings.AUTH_USER_MODEL)),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="legal_review_runs", to="documents.document")),
                ("review_profile", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="review_runs", to="legal_workspace.reviewprofile")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="review_runs", to="legal_workspace.legalworkspace")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="ContractFinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.CharField(db_index=True, max_length=64)),
                ("title", models.CharField(max_length=255)),
                ("severity", models.CharField(choices=[("critical", "严重"), ("high", "高"), ("medium", "中"), ("low", "低"), ("info", "提示")], db_index=True, default="medium", max_length=16)),
                ("evidence_type", models.CharField(choices=[("contract_text", "合同原文"), ("law", "法律依据"), ("internal_rule", "内部规则"), ("template", "标准模板"), ("historical_example", "历史案例")], default="contract_text", max_length=32)),
                ("risk_summary", models.TextField()),
                ("source_quote", models.TextField()),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                ("recommended_action", models.TextField(blank=True, default="")),
                ("suggested_replacement", models.TextField(blank=True, default="")),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("verification_status", models.CharField(choices=[("unverified", "未核验"), ("verified", "已核验"), ("needs_confirmation", "待确认"), ("rejected", "证据不成立")], db_index=True, default="unverified", max_length=32)),
                ("review_status", models.CharField(choices=[("pending", "待复核"), ("accepted", "已接受"), ("edited", "编辑后接受"), ("rejected", "已驳回"), ("needs_follow_up", "待补充")], db_index=True, default="pending", max_length=32)),
                ("reviewer_text", models.TextField(blank=True, default="")),
                ("sort_order", models.IntegerField(default=0)),
                ("legal_basis_annotations", models.ManyToManyField(blank=True, related_name="legal_findings_as_basis", to="annotations.annotation")),
                ("playbook_rule", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="findings", to="legal_workspace.playbookrule")),
                ("review_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="findings", to="legal_workspace.reviewrun")),
                ("source_annotation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="legal_findings_as_source", to="annotations.annotation")),
            ],
            options={"ordering": ("sort_order", "id")},
        ),
        migrations.CreateModel(
            name="ResearchRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.TextField()),
                ("jurisdiction", models.CharField(db_index=True, default="CN-MAINLAND", max_length=64)),
                ("cutoff_date", models.DateField(default=django.utils.timezone.localdate)),
                ("status", models.CharField(choices=[("pending", "等待执行"), ("retrieving", "检索资料"), ("drafting", "生成初稿"), ("verifying", "核验引用"), ("ready_for_review", "等待复核"), ("completed", "已完成"), ("failed", "失败"), ("cancelled", "已取消")], db_index=True, default="pending", max_length=32)),
                ("scope", models.JSONField(blank=True, default=dict)),
                ("answer", models.TextField(blank=True, default="")),
                ("limitations", models.TextField(blank=True, default="")),
                ("error_message", models.TextField(blank=True, default="")),
                ("model_name", models.CharField(blank=True, default="", max_length=128)),
                ("prompt_version", models.CharField(blank=True, default="", max_length=64)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_legal_research_runs", to=settings.AUTH_USER_MODEL)),
                ("source_annotations", models.ManyToManyField(blank=True, related_name="legal_research_runs", to="annotations.annotation")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="research_runs", to="legal_workspace.legalworkspace")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddConstraint(
            model_name="reviewprofile",
            constraint=models.UniqueConstraint(fields=("owner", "name", "version"), name="legal_unique_review_profile_version"),
        ),
        migrations.AddConstraint(
            model_name="playbookrule",
            constraint=models.UniqueConstraint(fields=("review_profile", "title"), name="legal_unique_rule_title_per_profile"),
        ),
        migrations.AddConstraint(
            model_name="contractfinding",
            constraint=models.CheckConstraint(condition=models.Q(("confidence__isnull", True), models.Q(("confidence__gte", 0.0), ("confidence__lte", 1.0), _connector="AND"), _connector="OR"), name="legal_finding_confidence_between_zero_and_one"),
        ),
        migrations.AddIndex(model_name="legalworkspace", index=models.Index(fields=["owner", "workspace_type"], name="legal_work_owner_i_63d9c5_idx")),
        migrations.AddIndex(model_name="legalworkspace", index=models.Index(fields=["owner", "matter_status"], name="legal_work_owner_i_2ea1f1_idx")),
        migrations.AddIndex(model_name="legalworkspace", index=models.Index(fields=["jurisdiction", "workspace_type"], name="legal_work_jurisdi_293d63_idx")),
        migrations.AddIndex(model_name="reviewprofile", index=models.Index(fields=["owner", "enabled"], name="legal_revi_owner_i_73935d_idx")),
        migrations.AddIndex(model_name="reviewprofile", index=models.Index(fields=["contract_type", "party_position", "jurisdiction"], name="legal_revi_contrac_83a773_idx")),
        migrations.AddIndex(model_name="playbookrule", index=models.Index(fields=["review_profile", "enabled", "sort_order"], name="legal_play_review__73bb20_idx")),
        migrations.AddIndex(model_name="playbookrule", index=models.Index(fields=["category", "severity"], name="legal_play_categor_38a677_idx")),
        migrations.AddIndex(model_name="reviewrun", index=models.Index(fields=["workspace", "status"], name="legal_revi_workspa_7f8326_idx")),
        migrations.AddIndex(model_name="reviewrun", index=models.Index(fields=["document", "created_at"], name="legal_revi_documen_6cb39a_idx")),
        migrations.AddIndex(model_name="reviewrun", index=models.Index(fields=["created_by", "created_at"], name="legal_revi_created_aab89a_idx")),
        migrations.AddIndex(model_name="contractfinding", index=models.Index(fields=["review_run", "severity", "sort_order"], name="legal_cont_review__0c099c_idx")),
        migrations.AddIndex(model_name="contractfinding", index=models.Index(fields=["review_run", "verification_status"], name="legal_cont_review__2909fb_idx")),
        migrations.AddIndex(model_name="contractfinding", index=models.Index(fields=["review_run", "review_status"], name="legal_cont_review__6d5193_idx")),
        migrations.AddIndex(model_name="researchrun", index=models.Index(fields=["workspace", "status"], name="legal_rese_workspa_a44901_idx")),
        migrations.AddIndex(model_name="researchrun", index=models.Index(fields=["created_by", "created_at"], name="legal_rese_created_fc5167_idx")),
        migrations.AddIndex(model_name="researchrun", index=models.Index(fields=["jurisdiction", "cutoff_date"], name="legal_rese_jurisdi_e86d54_idx")),
    ]
